CODIGO_A_IDIOMA = {
    'aa': 'afar',
    'ab': 'abjaso',
    'ace': 'achenés',
    'ach': 'acholi',
    'ada': 'adangme',
    'af': 'afrikáans',
    'afh': 'afrihili',
    'aka': 'acano',
    'akk': 'acadio',
    'ale': 'aleutiano',
    'am': 'amárico',
    'an': 'aragonés',
    'ang': 'inglés antiguo',
    'ar': 'árabe',
    'arc': 'arameo',
    'ars': 'árabe najdi',
    'arn': 'mapuche',
    'arp': 'arapaho',
    'art': 'artificial',
    'arw': 'arawak',
    'as': 'asamés',
    'ast': 'asturiano',
    'ava': 'avar',
    'ave': 'avéstico',
    'awa': 'awadhi',
    'ay': 'aimara',
    'az': 'azerí',
    'ba': 'baskir',
    'bal': 'baluchi',
    'bam': 'bambara',
    'ban': 'balinés',
    'bas': 'basa',
    'be': 'bielorruso',
    'bej': 'beya',
    'bem': 'bemba',
    'bg': 'búlgaro',
    'bh': 'bihari',
    'bho': 'bhojpuri',
    'bi': 'bislama',
    'bik': 'bicolano',
    'bin': 'edo',
    'bla': 'pie negro',
    'bn': 'bengalí',
    'bo': 'tibetano',
    'br': 'bretón',
    'bra': 'brijbhasha',
    'bs': 'bosnio',
    'bua': 'buriato',
    'bug': 'buguinés',
    'ca': 'catalán',
    'cad': 'caddo',
    'car': 'taíno',
    'ceb': 'cebuano',
    'ch': 'chamorro',
    'cha': 'chamorro',
    'chb': 'chibcha',
    'che': 'checheno',
    'chg': 'chagatay',
    'chm': 'mari',
    'cmn': 'mandarín',
    'cho': 'choctaw',
    'chr': 'cheroqui',
    'chu': 'eslavo eclesiástico antiguo',
    'chv': 'chuvasio',
    'chy': 'cheyene',
    'co': 'corso',
    'cr': 'cree',
    'cop': 'copto',
    'cor': 'córnico',
    'crh': 'tártaro de Crimea',
    'cre': 'cree',
    'cs': 'checo',
    'csb': 'casubio',
    'cy': 'galés',
    'da': 'danés',
    'dak': 'dakota',
    'de': 'alemán',
    'del': 'delaware',
    'din': 'dinka',
    'diu': 'diriku',
    'div': 'dhivehi',
    'doi': 'dogri',
    'dua': 'duala',
    'dum': 'neerlandés medio',
    'dyu': 'diula',
    'dz': 'dzongkha',
    'efi': 'efik',
    'egy': 'egipcio antiguo',
    'eka': 'acayo',
    'el': 'griego',
    'elx': 'elamita',
    'en': 'inglés',
    'enm': 'inglés medio',
    'eo': 'esperanto',
    'es': 'español',
    'eso': 'lengua de señas de Estonia',
    'et': 'estonio',
    'eu': 'euskera',
    'ewe': 'ewe',
    'ewo': 'ewondo',
    'fa': 'persa',
    'fan': 'fang',
    'fat': 'fante',
    'fi': 'finés',
    'fj': 'fiyiano',
    'fo': 'feroés',
    'fr': 'francés',
    'frm': 'francés medio',
    'fro': 'francés antiguo',
    'ful': 'fula',
    'fur': 'friulano',
    'fy': 'frisón',
    'ga': 'irlandés',
    'gaa': 'ga',
    'gay': 'gayo',
    'gd': 'gaélico escocés',
    'gez': 'yehén',
    'gil': 'kiribasiano',
    'gl': 'gallego',
    'gmh': 'alemán medio',
    'gn': 'guaraní',
    'goh': 'alemán antiguo',
    'gon': 'gondi',
    'got': 'gótico',
    'grb': 'grebo',
    'grc': 'griego antiguo',
    'gu': 'guyaratí',
    'gv': 'manés',
    'ha': 'hausa',
    'hai': 'haida',
    'haw': 'hawaiano',
    'he': 'hebreo',
    'her': 'herero',
    'hi': 'hindi',
    'hil': 'hiligainón',
    'hmo': 'hiri motu',
    'hr': 'croata',
    'hu': 'húngaro',
    'hup': 'hupa',
    'hy': 'armenio',
    'ia': 'interlingua',
    'iba': 'dayaco',
    'ibo': 'ibo',
    'id': 'indonesio',
    'ie': 'occidental',
    'ii': 'lolo de Sichuán',
    'ik': 'inupiaq',
    'ilo': 'ilocano',
    'io': 'ido',
    'is': 'islandés',
    'it': 'italiano',
    'iu': 'inuktitut',
    'ja': 'japonés',
    'jpr': 'judeopersa',
    'jrb': 'judeoárabe',
    'jv': 'javanés',
    'ka': 'georgiano',
    'kaa': 'karakalpako',
    'kab': 'cabil',
    'kac': 'kachín',
    'kam': 'kikamba',
    'kau': 'kau',
    'kaw': 'cavi',
    'kha': 'jasí',
    'kho': 'jotanés',
    'kik': 'kik',
    'kk': 'kazajo',
    'kl': 'groenlandés',
    'km': 'camboyano',
    'kn': 'kannada',
    'ko': 'coreano',
    'kok': 'konkani',
    'kom': 'kom',
    'kon': 'kon',
    'kos': 'kosraeano',
    'kpe': 'kpelle',
    'kru': 'curuj',
    'ks': 'cachemiro',
    'ku': 'kurdo',
    'kua': 'kua',
    'kum': 'kumyko',
    'kus': 'kusaal',
    'kut': 'kutenai',
    'kv': 'komi',
    'kw': 'córnico',
    'ky': 'kirguís',
    'la': 'latín',
    'lad': 'judeoespañol',
    'lah': 'landi',
    'lam': 'lamba',
    'lb': 'luxemburgués',
    'lez': 'lesguiano',
    'li': 'limburgués',
    'ln': 'lingala',
    'lo': 'lao',
    'lt': 'lituano',
    'lv': 'letón',
    'mdf': 'moksha',
    'mi': 'maorí',
    'mk': 'macedonio',
    'ml': 'malayalam',
    'mn': 'mongol',
    'mnc': 'manchú',
    'mo': 'moldavo',
    'mr': 'maratí',
    'ms': 'malayo',
    'mt': 'maltés',
    'my': 'birmano',
    'myv': 'erzya',
    'na': 'nauruano',
    'nah': 'náhuatl',
    'nap': 'napolitano',
    'nav': 'nav',
    'ne': 'nepalés',
    'nd': 'sindebele',
    'nds': 'bajo alemán',
    'nds-nl': 'bajo sajón neerlandés',
    'ng': 'ndonga',
    'nl': 'neerlandés',
    'nn': 'noruego nynorsk',
    'no': 'noruego bokmål',
    'nr': 'nrebele',
    'nv': 'navajo',
    'ny': 'chewa',
    'oc': 'occitano',
    'oj': 'ojibwe',
    'om': 'oromo',
    'or': 'oriya',
    'os': 'oseta',
    'pap': 'papiamento',
    'pi': 'pali',
    'pl': 'polaco',
    'ps': 'pastún',
    'pt': 'portugués',
    'qu': 'quechua',
    'rap': 'rapa nui',
    'rn': 'kirundi',
    'ro': 'rumano',
    'ru': 'ruso',
    'rw': 'ruandés',
    'sa': 'sánscrito',
    'sc': 'sardo',
    'sco': 'escocés',
    'sd': 'sindhi',
    'si': 'cingalés',
    'se': 'sami septentrional',
    'sk': 'eslovaco',
    'sl': 'esloveno',
    'sm': 'samoano',
    'smn': 'sami inari',
    'sn': 'shona',
    'so': 'somalí',
    'sq': 'albanés',
    'sr': 'serbio',
    'ss': 'swazi',
    'su': 'sundanés',
    'sv': 'sueco',
    'sw': 'swahili',
    'ta': 'tamil',
    'te': 'telugú',
    'tg': 'tayiko',
    'th': 'tailandés',
    'ti': 'tigriña',
    'tk': 'turcomano',
    'tl': 'tagalo',
    'tlh': 'klingon',
    'tn': 'setsuana',
    'to': 'tongano',
    'tpi': 'tok pisin',
    'tr': 'turco',
    'ts': 'xitsonga',
    'tt': 'tártaro',
    'tw': 'twi',
    'udm': 'udmurto',
    'ug': 'uigur',
    'uk': 'ucraniano',
    'ur': 'urdu',
    'uz': 'uzbeco',
    've': 'luvenda',
    'vi': 'vietnamita',
    'vo': 'volapuk',
    'vot': 'votio',
    'wa': 'valón',
    'wo': 'wolof',
    'xh': 'xhosa',
    'yi': 'yídish',
    'yo': 'yoruba',
    'yua': 'maya yucateco',
    'yue': 'cantonés',
    'za': 'chuan',
    'zh': 'mandarín',
    'zu': 'zulú',
    'afa': 'afroasiático',
    'alg': 'algonquiano',
    'apa': 'apache',
    'ath': 'atapasca',
    'bad': 'banda',
    'bai': 'bamileke',
    'bat': 'protobáltico',
    'ber': 'bereber',
    'bnt': 'bantú',
    'cai': 'lenguas centroamericanas',
    'cel': 'protocelta',
    'cau': 'lenguas caucásicas',
    'cus': 'cusito',
    'dra': 'dravídico',
    'fiu': 'protougrofinés',
    'him': 'himachalí',
    'ijo': 'iyo',
    'inc': 'índic',
    'ine': 'protoindoeuropeo',
    'ira': 'iraní',
    'iro': 'iroqués',
    'kar': 'karen',
    'khi': 'joisano',
    'kro': 'kru',
    'smi': 'sami',
    'wen': 'sórabo',
}

IDIOMA_A_CODIGO = {v: k for k, v in CODIGO_A_IDIOMA.items()}

CATEGORIAS_GRAMATICALES = [
    'sección',
    'abreviatura',
    'acrónimo',
    'adjetivo',
    'adjetivo cardinal',
    'adjetivo demostrativo',
    'adjetivo indefinido',
    'adjetivo indeterminado',
    'adjetivo interrogativo',
    'adjetivo numeral',
    'adjetivo ordinal',
    'adjetivo posesivo',
    'adjetivo relativo',
    'adverbio',
    'adverbio comparativo',
    'adverbio de afirmación',
    'adverbio de cantidad',
    'adverbio de duda',
    'adverbio de lugar',
    'adverbio de modo',
    'adverbio de negación',
    'adverbio de orden',
    'adverbio de tiempo',
    'adverbio demostrativo',
    'adverbio interrogativo',
    'adverbio relativo',
    'afijo',
    'artículo',
    'artículo determinado',
    'artículo indeterminado',
    'circunfijo',
    'conjunción',
    'conjunción adversativa',
    'conjunción ilativa',
    'dígrafo',
    'expresión',
    'forma verbal',
    'interjección',
    'letra',
    'locución',
    'locución adjetiva',
    'locución adverbial',
    'locución conjuntiva',
    'locución interjectiva',
    'locución prepositiva',
    'locución pronominal',
    'locución sustantiva',
    'locución verbal',
    'onomatopeya',
    'partícula',
    'postposición',
    'prefijo',
    'preposición',
    'preposición de ablativo',
    'preposición de acusativo',
    'preposición de acusativo o ablativo',
    'preposición de genitivo',
    'pronombre',
    'pronombre demostrativo',
    'pronombre indefinido',
    'pronombre interrogativo',
    'pronombre personal',
    'pronombre posesivo',
    'pronombre relativo',
    'refrán',
    'sigla',
    'sufijo',
    'sufijo flexivo',
    'sustantivo',
    'sustantivo ambiguo',
    'sustantivo animado',
    'sustantivo común',
    'sustantivo femenino',
    'sustantivo femenino y masculino',
    'sustantivo inanimado',
    'sustantivo masculino',
    'sustantivo neutro',
    'sustantivo neutro y masculino',
    'sustantivo propio',
    'sustantivo propio/pruebas',
    'símbolo',
    'verbo',
    'verbo auxiliar',
    'verbo impersonal',
    'verbo intransitivo',
    'verbo modal',
    'verbo perfectivo',
    'verbo pronominal',
    'verbo transitivo',
]

FORMAS_FLEXIVAS = [
    'forma sustantiva',
    'forma adjetiva',
    'forma verbal',
]